apiVersion: v1
kind: Pod
metadata:
    name: result-app-pod
    labels:
        name: result-app-pod
        app: demo-voting-app
spec:
    containers:
        - name: result-app
          #image: dockersamples/examplevotingapp_result
          image: dogdemo/examplevotingapp_result:latest
          ports:
              - containerPort: 80
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
