apiVersion: v1
kind: Pod
metadata:
    name: worker-app-pod
    labels:
        name: worker-app-pod
        app: demo-voting-app
spec:
    containers:
        - name: worker-app
          image: dogdemo/examplevotingapp_worker:latest
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
