apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
      annotations:
        container.apparmor.security.beta.kubernetes.io/system-probe: unconfined
    spec:
      serviceAccountName: datadog-agent
      containers:
      - name: datadog-agent
        image: datadog/agent:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8125
            hostPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            hostPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: api-key
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: KUBERNETES
            value: "true"
          - name: DD_HEALTH_PORT
            value: "5555"
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_PROCESS_AGENT_ENABLED
            value: "true"
          - name: DD_SYSTEM_PROBE_ENABLED
            value: "true"
          - name: DD_SYSTEM_PROBE_EXTERNAL
            value: "true"
          - name: DD_SYSPROBE_SOCKET
            value: /var/run/sysprobe/sysprobe.sock
          - name: DD_APM_ENABLED
            value: "true"
          - name: DD_APM_ENV
            value: "dev"
          - name: DD_APM_NON_LOCAL_TRAFFIC
            value: "true"
          - name: USE_DOGSTATSD
            value: "true"
          - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
            value: "true"
          - name: DD_LOGS_ENABLED
            value: "true"
          - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            value: "true"
          - name: DD_AC_EXCLUDE
            value: ""
          - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
            value: '{"service":"service","app":"app"}'
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "1500Mi"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: pointdir
            mountPath: /var/datadog-agent/run
          - name: logpodpath
            mountPath: /var/log/pods
          - name: logcontainerpath
            mountPath: /var/lib/docker/containers
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: debugfs
            mountPath: /sys/kernel/debug
          - name: s6-run
            mountPath: /var/run/s6
        livenessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      - name: system-probe
        image: datadog/agent:latest
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_RESOURCE
              - SYS_PTRACE
              - NET_ADMIN
        command:
          - /opt/datadog-agent/embedded/bin/system-probe
        env:
          - name: DD_SYSTEM_PROBE_ENABLED
            value: "true"
          - name: DD_SYSPROBE_SOCKET
            value: /var/run/sysprobe/sysprobe.sock
        resources:
          requests:
            memory: "150Mi"
            cpu: "200m"
          limits:
            memory: "150Mi"
            cpu: "200m"
        volumeMounts:
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: debugfs
            mountPath: /sys/kernel/debug
          - name: s6-run
            mountPath: /var/run/s6
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - hostPath:
            path: /var/datadog-agent/run
          name: pointdir
        - hostPath:
            path: /var/log/pods
          name: logpodpath
        - hostPath:
            path: /var/lib/docker/containers
          name: logcontainerpath
        - hostPath:
            path: /etc/passwd
          name: passwd
        - emptyDir: {}
          name: s6-run
        - hostPath:
            path: /sys/kernel/debug
          name: debugfs
